name: "[DEV] Deploy Workers"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-console-prod-*"

jobs:
  publish-workers-dev:
    uses: ./.github/workflows/template-deploy-workers-to-cloudflare.yaml
    with:
      rootDir: ./apps/execution-platform
      stage: prod
    secrets:
      cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
      cf_api_token: ${{ secrets.CF_API_TOKEN_WORKERS }}
