name: "Deploy Console DEV"

# on: [push]
on:
  release:
    types: [published]

jobs:
  publish-console-dev:
    uses: ./.github/workflows/template-deploy-to-cloudflare.yaml
    with:
      buildTarget: build:console:dev
      rootDir: ./apps/console
      distDir: ./dist
      branchName: main
      cfPagesName: flethy-console-dev
    secrets:
      cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
      cf_api_token: ${{ secrets.CF_API_TOKEN }}
