name: "[INT] Deploy Workers Cron"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-console-int-*"

jobs:
  publish-workers-dev:
    uses: ./.github/workflows/template-deploy-workers-to-cloudflare.yaml
    with:
      rootDir: ./apps/execution-platform-cron-trigger
      stage: int
    secrets:
      cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
      cf_api_token: ${{ secrets.CF_API_TOKEN_WORKERS }}
