name: "[PROD] Deploy Console"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-console-prod-*"

jobs:
  publish-console-dev:
    uses: ./.github/workflows/template-deploy-to-cloudflare.yaml
    with:
      buildTarget: build:console:prod
      rootDir: ./apps/console
      distDir: ./dist
      branchName: main
      cfPagesName: flethy-console-prod
    secrets:
      cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
      cf_api_token: ${{ secrets.CF_API_TOKEN }}
