name: "[PROD] Publish Connectors"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-connectors:
    uses: ./.github/workflows/template-publish-npm-package.yaml
    with:
      packageDir: ./packages/connectors
      packageScope: "@flethy/connectors"
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
