name: "[PROD] Publish Flow"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-flow:
    uses: ./.github/workflows/template-publish-npm-package.yaml
    with:
      packageDir: ./packages/flow
      packageScope: "@flethy/flow"
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
